GET http://localhost:3000/dogs/3

###
POST http://localhost:3000/dogs
Content-Type: application/json

{
"name": "fluffy",
"breed": "boxer",
"age": 2
}

###
PATCH http://localhost:3000/dogs/3
Content-Type: application/json

{
  "name": "fredo"
}

###
Delete http://localhost:3000/dogs/3